### ISSUE TITLE
Locize sends flat or nested json depending on the keys in the resource

### ISSUE THREAD

**Issue by scharf** [locize/i18next-locize-backend#290]
## Context

Suppose, you have most keys in your translation following the **nested** scheme (e.g. `"login.username"`, `"login.label"`, etc), then locize returns a resource with nicely **nested** JSON:

```json
{
    "login": {
        "label": "Log in",
        "user": "User Name"
    }
}
```
 Here is the german (`de`) translation (**nested**):
```json
{
    "login": {
        "user": "Benutzername"
    }
}
```

If you now add a key to `en` that does contain a space. (`"User not found!"`), then the resource returned by locize becomes **flat**:

```json
{
    "login.label": "Log in",
    "login.user": "User Name",
    "User not found!": "User not found!"
}
```

As long as there is not key with spaces in the `de` resource, then `de` continues to return the **nested** JSON:

```json
{
    "login": {
        "user": "Benutzername"
    }
}
```

##  Problem: i18next can read only flat or nested resource

The problem is, that i18next can deal **either** with *flat* or with *nested* resource. It cannot deal with cases where one language returns *nested* resource and the other language returns *flat* resource.

This can be very confusing, because if you [adjust the settings](https://www.i18next.com/principles/fallback.html#key-not-found) to deal with the *flat* `en` resource by using setting `keySeparator ` to `false`:

```js
{
  nsSeparator: false,
  keySeparator: false,
  //...
}
```

The `en` resource is loaded correctly, but it cannot find any translation in the `de` resource, because it tries to read it in *flat* mode..

## Solutions/Workarounds

- Make sure that all keys are always **nested** by forcing then to follow the nested pattern. E.g.:
  `i18next.t(key.replace(/[^\w\d.:]+/g,'.'));`
- Or force the resource to be **flat** by add key that contains spaces (e.g. `"Force flat!": "This forces flat JSON"`) and add it to **all** translations (else the translation may return *nested* instead of *flat* JSON) and set the   `keySeparator ` to `false`

**Comment by adrai** [comment]
Hi @scharf!

Thanks for posting this.

You recognized it correctly: locize automatically detects if a nested or flat json should be appropriate.

Is this an issue for your use case or is this intended as documentation?

**Comment by scharf** [comment]
@adrai I think this is a general problem: If you are using *nested* keys, and you use [saveMissing](https://www.i18next.com/configuration-options.html#missing-keys), you have to be very careful that you do not accidentally save a key that contains whitespace or other non nested key characters. 

> You recognized it correctly: locize automatically detects if a nested or flat json should be appropriate.

The problem is, that locize does recognize nested or flat json on a resource base and it can easily happen that one language uses *flat* and another uses *nested* keys. The real problem ist that i18next can only be configured to **either** recognize *nested* **or** recognize *flat* json, but not both.

So, we have a service (locize) that uses different format based on some heuristics on resource base and we have a library (i18next) that only be configured at a global level.

Nested keys are fragile: one key that does not follow the (not well specified) format of nested keys, the entire resource switches to *flat*. This makes the entire resource (=translation) unusable, if i18next is configured to use *nested* resources. I lost many hours debugging the problem and I was prepared to abandon locize, because I thought it is broken and cannot deliver the translations reliabley.

**The locize heuristics may be documented but it is unexpected.** Unless i18next can transparently deal with nested and flat resources.

Therefore, my suggestion is use force locize to use flat format and specify flat in i18next.

**Comment by adrai** [comment]
Thanks for your feedback.
I, personally have used saveMissing feature since I can remember...
Thanks to proper instrumentation of the code, I never had an issue to generate "wrong" keys.

To have locize forced to use flat format is not the correct way, in my opinion.

What you can do is overwrite the `getResource` function to lookup with your own "not matching" keySeparator i.e.: [https://jsfiddle.net/4g6n4a3y/](https://jsfiddle.net/4g6n4a3y/)

Is this something that may help?

**Comment by scharf** [comment]
> Is this something that may help?

Sure it would help. The point is not that I cannot find solutions for the problem. The point is that it is unexpected and it forced me to do a lot of debugging.

I like tools that simply work without me having to figure out subtile bugs. Logging a configuration problem on the console would have helped. But silently changing the format of a file that a service returns depending on its content is bad practice in my opinion. In particular if it becomes unreadable for the other side of the API.

Heck, the simple solutions would be:
- locize can be forced to a particular format for all resources
- i18next being able to transparently detect the JSON format and deal with it (how hard can it be to detect if the resource contqails nested or flat keys???).

If the provider of the API does some magic, the consumer should do so too. If the consumer does the magic and the provider of the API does not, it would not be a problem.

I am an old-school developer and for me an API is a [contract](https://en.wikipedia.org/wiki/Design_by_contract). Both sides have to understand the contract. There are rules how contracts can change. This contract is not well specified, because the guarantees (any resoure can be either flat or nested depending on my mood) do not match the expectations (all resources are either flat or nested).

**Comment by scharf** [comment]
> This contract is not well specified, because the guarantees (any resoure can be either flat or nested depending on my mood) do not match the expectations (all resources are either flat or nested).

Well, maybe that is not quite true: The contract are overly complicated (because the result format depends on the content of the result on a by resource basis). 

I also believe in [KISS](https://en.wikipedia.org/wiki/KISS_principle) and that is too complicated for my simple mind...

**Comment by adrai** [comment]
I am very sorry that this topic is causing you so much headache.
This has never been a problem for the last 2 years. (at least we never heard of it)

I would suggest that we continue to observe this and, in case of frequent occurrence, resume accordingly.

**Comment by adrai** [comment]
Seems we just got a backlog item in the next sprint to add an additional forced flat option ;-)

**Comment by mblarsen** [comment]
FWIW, I started using the lib today and ran into the exact same problem almost immediately. I solved it. But then my keys got polluted again by spaces. I had forgotten that was the problem, because it really does not make much sense and lost lots of time debugging the same issue. 

What would work for me was a user-land `mapMissing` function that is called before pushing to locize. 

E.g.

```
const mapMissing = (missing) => ({
  key: camelcase(slugify(missing)),
  translation: missing
})
```

**Comment by jamuhl** [comment]
@mblarsen you can force always nested by setting your locize project to publish format nested.

<img width="622" alt="Screenshot 2019-03-26 at 18 54 35" src="https://user-images.githubusercontent.com/977772/55021205-a4fc6980-4ff8-11e9-84e2-c732969a7fd4.png">

**Comment by mblarsen** [comment]
Neat, thanks @jamuhl

**Comment by Vadorequest** [comment]
Ran into this problem as well, spent hours debugging as well.

One simple workaround would be to force json nested for new projects by default.

**Comment by jamuhl** [comment]
@Vadorequest not that simple...i18next supports both json types: https://www.i18next.com/principles/fallback#key-not-found

**Comment by Vadorequest** [comment]
I don't understand the implications of what you're saying. I must be missing something.

**Comment by jamuhl** [comment]
You said: One simple workaround would be to force json nested for new projects by default. --> forcing this default would be forcing a default to your favor - but will punish the other users of i18next and locize having a non nested format...

**Comment by adrai** [comment]
It really depends on what i18n framework you are using, so the default could be nested or flat... that’s why the default is auto.
Regarding i18next it can be both. And what are new projects? Can be a customer is migrating from a self-hosted i18next solution.

**Comment by Vadorequest** [comment]
Then, maybe a notice on the settings page should be displayed depending on
the selected format? For instance I've selected i18next format and it could
display an explanation regarding this option, in order to highlight the
fact it should be decided instead of using the auto mode, which can be
surprisingly bad.

If choosing the default format is not a good option, then the best choice
is probably to educate the user about this.

**Comment by adrai** [comment]
Put it in the backlog...

**Comment by adrai** [comment]
Already released ;-)
fyi. there was already an explanation text for this in the settings page, we just added the publishFormat option in the project creation page.
![image](https://user-images.githubusercontent.com/1086194/70090298-27bed500-161a-11ea-9462-c7822313f09a.png)
