### ISSUE TITLE
Missing keys are not written to locize

### ISSUE THREAD

**Issue by pke** [locize/i18next-locize-backend#292]
I have created 2 keys in my locize account that are correctly read by the app.
However, keys and namespace that do not exist are never synced. As far as I could debug it they are put into the backend queue but the backends `process` is never called and therefor no `write` is performed.

This is my config:

```js
const i18n = use(LanguageDetector)
.use(reactI18nextModule)
.use(Locize)
.init({
  fallbackLng: "de",

  // have a common namespace used around the full app
  ns: ["translations", "about"],
  defaultNS: "translations",

  debug: true,
  saveMissing: true,

  interpolation: {
    escapeValue: false, // not needed for react!!
  },

  react: {
    wait: true,
  },

  backend: {
    //loadPath: "{{lng}}/{{ns}}",
    //parse: data => data,
    //ajax: loadLocales,
    projectId: "c02a....",
    apiKey: "8e1...",
  },
})
```

The keys should be added to the "about" namespace.

**Comment by jamuhl** [comment]
Hi Philipp,

Save missing will only be send if referenceLng in backend is defined.

```js
backend: {
    //loadPath: "{{lng}}/{{ns}}",
    //parse: data => data,
    //ajax: loadLocales,
    projectId: "c02a....",
    apiKey: "8e1...",
    referenceLng: 'de'
  },
```

**Comment by pke** [comment]
Wow that was a fast response and an important information. Maybe this should be more clear in the docs?
It works now (after the 10 sec debounce).
Thanks!
