### ISSUE TITLE
Unpublished locize resources

### ISSUE THREAD

**Issue by verys-jhuang** [locize/i18next-locize-backend#294]
Under the official locize documentation the way to "Fetch/filter the (unpublished) namespace resources" is to use the 
`https://api.locize.io/pull/{projectId}/{version}/{language}/{namespace}`
url.
https://docs.locize.com/integration/api

Is there any way to pull unpublished resource with `i18next-locize-backend`?

**Comment by jamuhl** [comment]
Why you need that. locize does publish on every change updates to the CDN.

Directly polling to from the database would result in bad performance.

What is your use case to want to have to load the data from the database?

**Comment by jamuhl** [comment]
I guess i see...sorry...did not check from which company you come. If i get it right you do want to ensure that content gets not exposed to S3 - so like to pull from database. Right

**Comment by verys-jhuang** [comment]
The use case we want to have is to have two different apis:
DEV and LIVE.
DEV will always be unpublished (information only used for development instances) and accessed by api key only.

**Comment by verys-jhuang** [comment]
yup! exactly

**Comment by jamuhl** [comment]
give me a few minutes...will extend the backend to enable this.

**Comment by jamuhl** [comment]
Ok...i guess you already set autopublish to false for your DEV and LIVE versions in locize.

In i18next-locize-backend@1.5.0 you now can set `pull: true` on init (just make sure you got an APIKey added valid for DEV) and you should now load directly from database.

We will check for an additional option to make the CDN publish secure -> so those files could be only accessed having an APIKey (so you could toggle that for each version) - that would be better regarding performance - but i guess current option to pull let you start your work without risking leaking confidential informations.

**Comment by jamuhl** [comment]
For LIVE make sure you read https://faq.locize.com/misc/latency-optimization-tips-for-optimal-performance if you like to use the CDN published files in production - using cache and resulting egde location usage improves performance highly

**Comment by verys-jhuang** [comment]
awesome thanks for the super quick support!  just checked and it seems to be working!
