### ISSUE TITLE
ie9 not working with  i18next-locize-backend

### ISSUE THREAD

**Issue by NovakAn** [locize/i18next-locize-backend#295]
These are my dependencies related to i18next: 
"react": "15.4.2",
"i18next-locize-backend": "1.4.2"
"i18next": "11.2.2",
"react-i18next": "7.6.0",
"i18next-browser-languagedetector": "2.2.0",

I get an error trying to get anything from api.locize.io/... on ie9.
In console I get an error: {description: "Access is denied", message: "Access is denied", name: "Error", number: -2147024891}
When I disable i18next-locize-backend and put "resources" in init method I do not get that error.

I am also getting two errors (with backend and without): "Unhandled promise rejection Error: Cannot parse given Error object", but I am not sure they are related to i18next.

Other versions and browsers work ok.

**Comment by jamuhl** [comment]
Guess ie <10 does not support CORS (so you can't access cross origin resources). If you need to support IE9 you either will need to create a proxy to serve translations from your own server or create a custom backend with fallback to eg. https://github.com/jpillora/xdomain for IE9.
