### ISSUE TITLE
Typescript typings?

### ISSUE THREAD

**Issue by danawoodman** [locize/i18next-locize-backend#297]
Trying to use this with Typescript but getting the following error:

```
Type error: Could not find a declaration file for module 'i18next-locize-backend'. '/Users/foo/bar/node_modules/i18next-locize-backend/dist/commonjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/i18next-locize-backend` if it exists or add a new declaration (.d.ts) file containing `declare module 'i18next-locize-backend';`  TS7016

    1 | import i18n from 'i18next'
  > 2 | import Backend from 'i18next-locize-backend'
      |                     ^
    3 | import LanguageDetector from 'i18next-browser-languagedetector'
    4 | import { reactI18nextModule } from 'react-i18next'
    5 | import { LOCIZE_PROJECT_ID, LOCIZE_API_KEY } from './constants'
```

Any plans to add Typescript support?

**Comment by jamuhl** [comment]
@danawoodman if you like you can add typescript definitions in a PR?

**Comment by danawoodman** [comment]
If only I had the time, I would! 😢

**Comment by jamuhl** [comment]
might be i could copy most from here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/i18next-xhr-backend/index.d.ts

**Comment by Boscop** [comment]
@jamuhl Are `locize-lastused` and `locize-editor` also supposed to work with TypeScript? I'm getting:
```
TS7016: Could not find a declaration file for module 'locize-lastused'. 'node_modules/locize-lastused/dist/commonjs/index.js' implicitly has an 'any' type.
Try `npm install @types/locize-lastused` if it exists or add a new declaration (.d.ts) file containing `declare module 'locize-lastused';` 

TS7016: Could not find a declaration file for module 'locize-editor'. 'node_modules/locize-editor/dist/commonjs/index.js' implicitly has an 'any' type.
Try `npm install @types/locize-editor` if it exists or add a new declaration (.d.ts) file containing `declare module 'locize-editor';` 
```

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/pull/1248 seems sufficient to get it working...no types needed for the modules themself...you init those using the i18next init call

**Comment by Boscop** [comment]
@jamuhl That's what I though, but then why am I getting the above errors when I outcomment those lines?
```js
[...]

// import LastUsed from "locize-lastused";
// import Editor from "locize-editor";

i18n
  .use(Backend)
  // .use(LastUsed)
  // .use(Editor)
  .use(LangDetector)
  .use(initReactI18next)
  .init({

[...]
```

**Comment by jamuhl** [comment]
not sure...but in the end typescript is just javascript...never used it myself...as i don't see a big benefit in it (more pain - than gain) -> but there might be an option to just ignore this -> in the end those are no real errors...just typescript not finding types...

**Comment by Boscop** [comment]
Thanks, this worked: https://stackoverflow.com/a/50516783

**Comment by Boscop** [comment]
@jamuhl Sorry for this off-topic question, but I haven't found the answer in the docs: Does `saveMissing` only cause missing values to be saved, or also missing keys? E.g. if `t("FOO")` is called but `FOO` doesn't exist on locize yet, will it be saved to locize somewhere?

**Comment by jamuhl** [comment]
`t(key)` -> will add that key
`t(key, value)` -> will add key with given value
`t(key, value, context)` -> will add key with value and also add context as information to that segment
