### ISSUE TITLE
Node process never exiting as a result of default reloadInterval option

### ISSUE THREAD

**Issue by blazingarrow** [locize/i18next-locize-backend#300]
I'm using the _i18next-locize-backend_ inside a gulp task and I'm having the problem that the task never exiting. After looking into the code of  _i18next-locize-backend_ I've found that the _reloadInterval_  has a default value. Is this the intended behaviour? 

Unfortunately setting the option to `reloadInterval: false` has no effect because the _Backend._createClass function is executed twice 🤔. So the interval is set on the first run.

Any help appreciated.

```js
const i18next = require('i18next');
const LocizeBackend = require('i18next-node-locize-backend');
const backendOptions = {
    projectId: process.env.LOCIZE_PROJECT_ID,
    apiKey: process.env.LOCIZE_API_KEY,
    referenceLng: process.env.LOCIZE_REFERENCE_LANGUAGE,
    version: process.env.LOCIZE_VERSION,
    reloadInterval: false
};

export function loadTemplates() {
    return i18next
    .use(LocizeBackend)
    .init({
        debug: false,
        initImmediate: false,
        lng: 'de-CH',
        load: 'de-CH',
        preload: ['de-CH', 'fr-CH', 'it-CH'],
        defaultNS: 'basic',
        ns: ['basic'],
        returnObjects: true,
        backend: backendOptions
    });
}

export function getI18n() {
    return i18next;
}

```

**Comment by jamuhl** [comment]
Did you solve this -> or just moving to the right repo?

Just made a fix which might help: https://github.com/locize/i18next-node-locize-backend/commit/095f94046168b05ec25bfc620c65c6b761d16590

**Comment by jamuhl** [comment]
could you try i18next-node-locize-backend@2.4.2

**Comment by blazingarrow** [comment]
@jamuhl sorry for messing up with the repository. I've just tried _i18next-node-locize-backend@2.4.2_ and it works perfectly. Thank you!

**Comment by jamuhl** [comment]
Awesome...thank you for confirming
