### ISSUE TITLE
Missing keys not saving to locize account

### ISSUE THREAD

**Issue by jan-brzeski** [locize/i18next-locize-backend#301]
This is my i18n config. On application loading - i see in console some logs from i18next, that some keys are missing, but they do not automatically adding into account to my language. What have I missed?

```

import i18n from 'i18next';
import detector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';
import Locize from 'i18next-locize-backend';

const backend = {
  projectId: 'key..',
  apiKey: '...key',
  referenceLng: 'en',
  allowedAddOrUpdateHosts: ['https://test.host'],
};

i18n
  .use(detector)
  .use(Locize)
  .use(initReactI18next)
  .init({
    backend,
    fallbackLng: 'en',
    react: {
      wait: true,
    },
    debug: process.env.NODE_ENV === 'development',
    saveMissing: true,
    saveMissingTo: 'all',
  });

export default i18n;
```

**Comment by jamuhl** [comment]
Did you find the problem...my guess at looking at the config (which seems ok) is the page was not loaded in `en` --- but just guessing.

**Comment by haf** [comment]
>   allowedAddOrUpdateHosts: ['https://test.host'],

This line is wrong, it must be `allowedAddOrUpdateHosts: ['test.host']`
