### ISSUE TITLE
replacing https://api.locize.io to internal project api

### ISSUE THREAD

**Issue by cullsin** [locize/i18next-locize-backend#304]
Hello, 

We are having a requirement to wrap around locize fetched data. So we would like to change the api from "https://api.locize.io" to our "https://api.site.com". Our site internally fetch locize information and do the purpose. The problem here is the URL is hard-coded in the npm module. Is it possible to pass the api host as an argument ? . Otherwise, please suggest me the work around on this.

**Comment by jamuhl** [comment]
Hi @cullsin, you can either set the `loadPath` in the init options: https://github.com/locize/i18next-locize-backend/blob/master/src/index.js#L28 aside of the other options needed. 

Or use the regular xhr backend coming with i18next (https://github.com/i18next/i18next-xhr-backend) when loading from your own server.
