### ISSUE TITLE
Error on gatsby build

### ISSUE THREAD

**Issue by luisgrandegg** [locize/i18next-locize-backend#311]
Hi,
First of all congrats on an awesome util :)

This issue is somehow related to https://github.com/locize/i18next-locize-backend/issues/305

We are building our multilanguage site using gatsby + locize and we have a problem when building our application with gatsby. In the build phase, window is not defined and so the following lines fail.

https://github.com/locize/i18next-locize-backend/blob/master/src/index.js#L22
https://github.com/locize/i18next-locize-backend/blob/master/src/index.js#L71

I've played around a little bit and checking for window type seems to work corretcly, like it's done in this other i18next plugin.

https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/path.js#L6

Are you open to a PR? It would save us having to do some nasty things with webpack

Thanks in advance for your time

**Comment by jamuhl** [comment]
Sure...PR is very welcome...👍

**Comment by saqueib** [comment]
@luisgrandegg @jamuhl Hey Man need little help with setup on gatsby, I am using gatsby-plugin-react-i18next which gives options to configure this plugin from `gatsby-config.js` file 

```js
{
      resolve: `gatsby-plugin-react-i18next`,
      options: {
        localeJsonSourceName: `locale`, // name given to `gatsby-source-filesystem` plugin.
        languages: [`en`],
        defaultLanguage: `en`,
        // if you are using Helmet, you must include siteUrl, and make sure you add http:https
        // siteUrl: `http://localhost:8000/`,
        // you can pass any i18next options
        i18nextOptions: {
          debug: process.env.NODE_ENV === 'development',
          interpolation: {
            escapeValue: false // not needed for react as it escapes by default
          },
        }
      }
    }
```

But all the code sample I can find are in Pure React where you can just do 

```js
import i18next from 'i18next';
import Backend from 'i18next-locize-backend';

i18next
  .use(Backend)
  .init({
    backend: {
      projectId: '[PROJECT_ID]',
      apiKey: '[API_KEY]',
      referenceLng: 'en'
    }
  });
```

How can I integrate `locize backend` with Gatsby please help?

**Comment by adrai** [comment]
> @luisgrandegg @jamuhl Hey Man need little help with setup on gatsby, I am using [gatsby-plugin-react-i18next](https://www.gatsbyjs.com/plugins/gatsby-plugin-react-i18next/) which gives options to configure this plugin from `gatsby-config.js` file
> 
> ```js
> {
>       resolve: `gatsby-plugin-react-i18next`,
>       options: {
>         localeJsonSourceName: `locale`, // name given to `gatsby-source-filesystem` plugin.
>         languages: [`en`],
>         defaultLanguage: `en`,
>         // if you are using Helmet, you must include siteUrl, and make sure you add http:https
>         // siteUrl: `http://localhost:8000/`,
>         // you can pass any i18next options
>         i18nextOptions: {
>           debug: process.env.NODE_ENV === 'development',
>           interpolation: {
>             escapeValue: false // not needed for react as it escapes by default
>           },
>         }
>       }
>     }
> ```
> 
> But all the code sample I can find are in Pure React where you can just do
> 
> ```js
> import i18next from 'i18next';
> import Backend from 'i18next-locize-backend';
> 
> i18next
>   .use(Backend)
>   .init({
>     backend: {
>       projectId: '[PROJECT_ID]',
>       apiKey: '[API_KEY]',
>       referenceLng: 'en'
>     }
>   });
> ```
> 
> How can I integrate `locize backend` with Gatsby please help?
> 
> Also need to make `InContext Editor` work for our usecase

The best way to integrate locize with gatsby is probably by using the [CLI](https://github.com/locize/locize-cli).
An example on how this could be done is defined here in Step 1: https://github.com/locize/react-tutorial

Regarding the InContext Editor, just make sure you include the [locize script](https://github.com/locize/locize)
either by just loading it as external script: `<script src="https://unpkg.com/locize/locize.min.js" />`
or by having it as an npm dependency and just importing it somewhere `import "locize";`
