### ISSUE TITLE
Non-matching hostname while using function for allowedAddOrUpdateHosts causes error

### ISSUE THREAD

**Issue by joshua-turner** [locize/i18next-locize-backend#314]
When using a function to check valid hostnames via `allowedAddOrUpdateHosts`, if it returns false it's still caught by the logger and assumes the `allowedAddOrUpdateHosts` param is an array and tries to .join(',') it.

https://github.com/locize/i18next-locize-backend/blob/a79661955e94262911d956772e7c484950a17b27/src/index.js#L70-L79

Like above, there needs to be an explicit type check of that param before assuming it's an array.

**Comment by adrai** [comment]
Thank you very much...
released in 3.0.1
