### ISSUE TITLE
Scrape all missing keys and send them to Locize backend

### ISSUE THREAD

**Issue by rwieruch** [locize/i18next-locize-backend#315]
Thanks for this project! 

As far as I understand, if I am using the following config for my `i18next`, I get all the missing keys send to the Locize backend once they are rendered (in React).

```
saveMissing: true,
saveMissingTo: 'all',
```

It's easy to not spot a missing key this way, because it may be hidden in some closed Dialog component. Is there a way to scrape all the missing keys for the entire application across all languages and namespaces and send them to the Locize backend? 

Or is this something Locize CLI is doing? I couldn't find anything about it.

**Comment by adrai** [comment]
You may have a look at:
https://github.com/i18next/i18next-parser or https://github.com/i18next/i18next-scanner
=> https://github.com/locize/i18next-node-locize-backend/issues/2#issuecomment-387412386

**Comment by rwieruch** [comment]
Any plans to make this a feature of Locize sometime in the future? Would want to run my own extraction script on the side.

**Comment by adrai** [comment]
May I ask how you imagine this to be a feature of locize? What do you expect to be different to i18next-parser oder i18next-scanner?
I'm curious to know your ideas.

**Comment by rwieruch** [comment]
> May I ask how you imagine this to be a feature of locize? What do you expect to be different to i18next-parser oder i18next-scanner?
> I'm curious to know your ideas.

Maybe just another npm script / i18n plugin which uses `i18next-parser` under the hood and sends all missing keys at once to the Locize backend. Otherwise I cannot be always sure to have all missing keys in Locize, can I?

**Comment by adrai** [comment]
Will discuss this topic in the next weeks...

**Comment by adrai** [comment]
Seems you can just create an npm script which will do something like this:

i.e. having an `i18next-parser.config.js` file like this:
```javascript
module.exports = {
  defaultNamespace: 'translation',
  // Default namespace used in your i18next config

  defaultValue: '',
  // Default value to give to empty keys

  locales: ['en', 'de'],
  // An array of the locales in your applications

  namespaceSeparator: ':',
  // Namespace separator used in your translation keys
  // If you want to use plain english keys, separators such as `.` and `:` will conflict. You might want to set `keySeparator: false` and `namespaceSeparator: false`. That way, `t('Status: Loading...')` will not think that there are a namespace and three separator dots for instance.

  output: 'locales/$LOCALE/$NAMESPACE.json',
  // Supports $LOCALE and $NAMESPACE injection
  // Supports JSON (.json) and YAML (.yml) file formats
  // Where to write the locale files relative to process.cwd()
}
```

```sh
i18next '/path/to/file/or/dir' && locize sync --format json --path ./locales
```

Is this ok?

**Comment by rwieruch** [comment]
Didn't know about the `sync`. This helps, yeah! Thank you 👍
