### ISSUE TITLE
Reference Language is pre-filled with defaults

### ISSUE THREAD

**Issue by rwieruch** [locize/i18next-locize-backend#316]
On https://www.locize.app I use the reference language 'en' for my project. 

My application has the following configuration:

```
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

import LocizeBackend from 'i18next-locize-backend';
import LocizeEditor from 'locize-editor';

i18n
  .use(LocizeBackend)
  .use(LocizeEditor)
  .use(initReactI18next)
  .init({
    debug: true,

    lng: 'en',
    whitelist: ['en', 'de'],
    fallbackLng: false,

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },

    saveMissing: true,
    saveMissingTo: 'all',

    backend: {
      projectId: 'my-project-id',
      apiKey: 'my-api-key',
      referenceLng: 'en',
    },
  });

export default i18n;
```

Since I am using the `saveMissing` and `saveMissingTo` flags, I get all the updates in my Locize project. However, all the keys for the reference language are already done.

![Screenshot 2020-02-04 at 17 24 51](https://user-images.githubusercontent.com/2479967/73765019-3d648e00-4774-11ea-9ce4-9dd302d45703.png)

That's because for the reference language all the default keys are used:

![Screenshot 2020-02-04 at 17 25 09](https://user-images.githubusercontent.com/2479967/73765083-553c1200-4774-11ea-9811-0329d4dee589.png)

Whereas they are not used for any other language:

![Screenshot 2020-02-04 at 17 25 16](https://user-images.githubusercontent.com/2479967/73765108-5d944d00-4774-11ea-95ae-ca5e8090b91a.png)

Is there a way to avoid this behavior and keep the reference list empty as well?

**Comment by adrai** [comment]
You mean save missing keys without any value?

**Comment by rwieruch** [comment]
But then I will always start with a complete translated list of keys for the reference language. Even though these are just the default values. Instead, I would want to give over the project to my translators who can then see all the missing translations rather than a complete list.

**Comment by adrai** [comment]
Normally 1 language should be translated. This can also be a "dev" language. So the translators can translate from -> to a language.
Btw. there is a filter you can use to get all keys created via "save missing": 
![image](https://user-images.githubusercontent.com/1086194/73820903-0b464100-47f3-11ea-9623-6002963873d0.png)

**Comment by rwieruch** [comment]
Thanks @adrai I think having a dev language makes sense 👍

**Comment by jamuhl** [comment]
As a quick hint...you can also pass a defaultValue with the saveMissing feature by calling `t` with a second param: `i18n.t('key', 'defaultValue')` (additional 3rd would set context).
