### ISSUE TITLE
load only selected namespace on page load

### ISSUE THREAD

**Issue by cullsin** [locize/i18next-locize-backend#318]
Hi, 

we have configured locize + i18next. When we do benchmark, On the initial load i18next configuration takes 2sec to load and allow user to perform the action in the homepage. I have presented our configuration below. I would like to  load namespace only required in the homepage, instead of load all namespace.

Please suggest me.

Can you please help me optimizing locize.

              /** @format */

          import i18n from 'i18next';
          import moment from 'moment';
          import LocizeEditor from 'locize-editor';
          import LocizeBackend from 'i18next-locize-backend';
          import LanguageDetector from 'i18next-browser-languagedetector';

          import { captureException } from '@sentry/browser';
          import { reactI18nextModule } from 'react-i18next';
          import { getLocaleBasedOnHost } from 'utils/i18nHelper';

          const { locale, version, backendUrl } = getLocaleBasedOnHost();

          i18n
            .use(LocizeBackend)
            .use(LocizeEditor)
            .use(LanguageDetector)
            .use(reactI18nextModule)
            .init(
              {
                lng: locale,
                fallbackLng: 'sv-SE',
                debug: false,
                ns: [
                  'lang_1',
                  'lang_2',
                  'lang_3',
                  'lang_4',
                  'lang_5',
                  'lang_6',
                  'lang_7',
                  'lang_8',
                  'lang_9',
                  'lang_10',
                  'lang_11',
                  'lang_12',
                  'lang_13',
                  'lang_14',
                  'lang_15'
                ],
                defaultNS: 'lang_2',
                interpolation: {
                  escapeValue: false,
                  format(value, format) {
                    // date formatting for locales
                    if (format) {
                      return moment(value).format(format);
                    }
                    return value;
                  }
                },
                backend: {
                  projectId: '3265de08-cdc0-4c54-9b90-0363b49f3f7a', // <-- replace with your projectId
                  referenceLng: 'sv-SE',
                  version: version,
                  loadPath: `${backendUrl}{{projectId}}/{{version}}/{{lng}}/{{ns}}`
                },
                returnObjects: true,
                  load: 'currentOnly',
                react: {
                  wait: true
                  //omitBoundRerender: false,
                }
              },
              (error) => {
                if (error) {
                  // Sending error to sentry
                  captureException(error);
                }
              }
            );

          export default i18n;

**Comment by adrai** [comment]
If I have understood correctly, the only thing you have to do is remove the ns option completely.
This should load the namespace on demand.
