### ISSUE TITLE
Can't find variable document on react-native

### ISSUE THREAD

**Issue by maximilize** [locize/i18next-locize-backend#321]
This module is not only used by projects using browsers. In react-native for example, the global `document` does not exist.
This commit is breaking our code: https://github.com/locize/i18next-locize-backend/commit/f765fddb33d75353c82d2ae0da82f6bf020d15ec

**Comment by adrai** [comment]
I'm sorry, can you try with v3.1.1 ?

**Comment by adrai** [comment]
@maximilize Is it ok for you with v3.1.1?

**Comment by maximilize** [comment]
Sorry for the late reply. It's working now, thanks for fixing it so quick.
