### ISSUE TITLE
Prevent the usage in production builds

### ISSUE THREAD

**Issue by maximilize** [locize/i18next-locize-backend#322]
Shame on me that it happened that we used locize in a production build. However, to prevent this for other devs, something like this might be a solution:

```javascript
if (typeof __DEV__ !== 'undefined' && !__DEV__) throw new Error('The locize backend is not allowed in production builds');
```

or 

```javascript
if (process.env.NODE_ENV === 'production') throw new Error();
```

**Comment by adrai** [comment]
Hehe, it’s not so simple...
the i18next-locize-backend can and should be used in production, at least to load translations fromour CDN.
But probably not to saveMissing/updateMissing in production (but also this makes sense in some production situations...)

**Comment by maximilize** [comment]
Yeah I know it's not this easy, just wanted to throw this in as an inspiration.
I added such code to our app now to prevent such issues in the future :smile:

**Comment by adrai** [comment]
v4.0.3 will at least warn if you're using saveMissing/updateMissing feature on non localhost
