### ISSUE TITLE
Save missing keys / values not working

### ISSUE THREAD

**Issue by LavaToaster** [locize/i18next-locize-backend#323]
So in my app, I've been debugging for quite some time why I couldn't get missing values to be saved into the locize service despite configuring it to.

I'm _pretty_ certain I've isolated it down to the following in my particular case:

In this area: https://github.com/locize/i18next-locize-backend/blob/41df013888e36231fef062a65f4773c5814990a9/lib/index.js#L235-L252

If the code makes it to the following where it goes out to request languages:

```
    this.getLanguages((err) => {
      if (err && err.message && err.message.indexOf('does not exist') > 0) {
        if (callback) return callback(err)
        logger.error(err.message)
      }
    })
```

The only time it calls the callback is if there an error, but if the request should succeed, then it doesn't call back.

I would submit a PR for this, but I wanted to check with you if this is right, and intended behaviour. The moment I added line to call the callback, things started working for me.

**Comment by LavaToaster** [comment]
This is a separate issue, but node is throwing errors when you define `"type": "module"` due to there being a mix of module types in here. I also encounted this on `locize-lastused`.

```
2020-04-26T05:32:34.987Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"Must use import to load ES Module: /var/task/node_modules/i18next-locize-backend/cjs/index.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/node_modules/i18next-locize-backend/cjs/index.js from /var/task/.next/serverless/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename /var/task/node_modules/i18next-locize-backend/cjs/index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/i18next-locize-backend/package.json.\n","code":"ERR_REQUIRE_ESM","stack":["Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/i18next-locize-backend/cjs/index.js","require() of ES modules is not supported.","require() of /var/task/node_modules/i18next-locize-backend/cjs/index.js from /var/task/.next/serverless/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.","Instead rename /var/task/node_modules/i18next-locize-backend/cjs/index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/node_modules/i18next-locize-backend/package.json.","","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)","    at Module.load (internal/modules/cjs/loader.js:1002:32)","    at Function.Module._load (internal/modules/cjs/loader.js:901:14)","    at Module.require (internal/modules/cjs/loader.js:1044:19)","    at require (internal/modules/cjs/helpers.js:77:18)","    at Object.G8bO (/var/task/.next/serverless/pages/index.js:705:18)","    at __webpack_require__ (/var/task/.next/serverless/pages/index.js:23:31)","    at Module.cha2 (/var/task/.next/serverless/pages/index.js:2147:40)","    at __webpack_require__ (/var/task/.next/serverless/pages/index.js:23:31)","    at Module.91Bm (/var/task/.next/serverless/pages/index.js:463:17)"]}
```

**Comment by adrai** [comment]
I can’t reproduce this.
Can you create an example repo?

**Comment by adrai** [comment]
regarding the callback problem, can you try v4.0.5?

**Comment by LavaToaster** [comment]
So I can only reproduce this right now on Vercel's service (Formaly ZEIT Now).

https://github.com/LavaToaster/locize-module-issue

Commit history isn't in the greatest shape as I had to remove and re-add this project to demo the issue.

- This [commit add the package](https://github.com/LavaToaster/locize-module-issue/commit/91c2d0ddb73b8f09672076e4556f5a37dfefa266) and deployed it here - https://locize-module-issue-3ce5bmwmf.now.sh - you can see it returns a 502

- This [commit removes the package](https://github.com/LavaToaster/locize-module-issue/commit/ce1b395131c2010aeb3941b63dd93d7ff8440750) and deployed it here -
https://locize-module-issue-jd8mefcio.now.sh - you can see it returns normally

To setup the repo all I did was the following

```
yarn create next-app locize-issue
yarn add i18next-locize-backend
```

I then modified `pages/index.js` for the following

Import the package:
```
import Locize from 'i18next-locize-backend';;

console.log(Locize);
```

and further down force it to use server side rendering, instead of static site generation

````
Home.getInitialProps = async() => {
  return {};
}
```

Hopefully that helps!

**Comment by adrai** [comment]
Can you try to import it like this?
`import Locize from 'i18next-locize-backend/cjs'; `

**Comment by adrai** [comment]
I'm not familiar with Vercel and I don't know how Vercel works behind the scene. But seems the module resolution is not exactly like the original node.js runtime or they are transpiling something... 

Normally, having the package.json defined like this: https://github.com/locize/i18next-locize-backend/blob/master/package.json#L17
should work for `const Locize = require('i18next-locize-backend')` or `import Locize from 'i18next-locize-backend'`

Maybe @rauchg knows more 🤷‍♂️

**Comment by LavaToaster** [comment]
🤷 https://github.com/LavaToaster/i18next-locize-backend/commit/06d3c740d9696df92608930f52fe123f09912c86

That's all I did to make it work for me in next.js.

This does sound like a weird issue with newer node versions and webpack to be honest. 

I did see that another package had some issues with this recently (like within a day!), not sure if you can gather any insight here https://github.com/then/is-promise/issues/14

**Comment by adrai** [comment]
strange... testing on different node.js versions with require(‘i18next-locize-backend‘) or import x from ‘i18next-locize-backend‘
works correctly... loads what is in cjs for commonjs and loads from lib for esm...

I would not change the type of the package.json but rather import ‘i18next-locize-backend/cjs‘ if needed.
this works so you don’t need to maintain a fork

**Comment by adrai** [comment]
probably the problem is somewhere here: https://github.com/zeit/now/blob/master/packages/now-node/src/index.ts#L263 @styfle ?

**Comment by adrai** [comment]
Vercel: ![image](https://user-images.githubusercontent.com/1086194/80864807-57cfda00-8c85-11ea-9fb9-d731479e38d3.png)
https://github.com/zeit/now/issues/3337#issuecomment-556141731

**Comment by Vadorequest** [comment]
Using Versel too and running into an issue that looks similar, my missing keys aren't created on Locize anymore. Note that this used to work a few months ago.

```
[ error ] ./src/utils/i18n/i18nextLocize.ts
Module not found: Can't resolve 'i18next-locize-backend/dist/cjs' in '/Users/vadorequest/dev/next-right-now/src/utils/i18n'

``` 

I've tried both /dist/cjs and /cjs but none work.

![image](https://user-images.githubusercontent.com/3807458/81352795-afc47180-90c7-11ea-9ade-0fffa15294c9.png)

But I'm using v3.1.1, gonna update and retry.

**Comment by Vadorequest** [comment]
After upgrading to 4.0.7, and testing locally only (not on Vercel).

Using `import i18nextLocizeBackend from 'i18next-locize-backend';` fails with TS error:

![image](https://user-images.githubusercontent.com/3807458/81353352-18f8b480-90c9-11ea-8c7c-44c41eedb0c4.png)

Using `import i18nextLocizeBackend from 'i18next-locize-backend/cjs'` doesn't generate any TS error, but my missing keys aren't saved anyway (running locally).

---

Browser console:
![image](https://user-images.githubusercontent.com/3807458/81353595-c10e7d80-90c9-11ea-9d63-16bddb857e1d.png)

I do get messages like `i18next::translator: missingKey fr common nav.productsPage.link Produits`, but nothing happens on Locize.

Server logs, with additional logs that show the `send` function does `emit` missingKey event:
![image](https://user-images.githubusercontent.com/3807458/81353719-19de1600-90ca-11ea-88d9-4b6864a96ce9.png)


I thought my bug was related to this issue, but I'm not sure anymore, because mine happens locally. saveMissing is enabled and apiKey is provided.

Commit: https://github.com/UnlyEd/next-right-now/commit/7ac2100303f9a0fc7595118e10e71d3dd5829361
PR: https://github.com/UnlyEd/next-right-now/pull/42

**Comment by adrai** [comment]
@Vadorequest save missing seems to work...
Can you open an other issue and add more information?
How does your save missing request look like? Show your network tab...
If you prefer you can also send an email at support@locize.com
