### ISSUE TITLE
SaveMissing not triggered & missing keys are not saved with "ERR_FAILED" API error

### ISSUE THREAD

**Issue by Vadorequest** [locize/i18next-locize-backend#324]
I'm migrating my Next.js SSR app into a SSG app, all pages were using SSR before, and now most of use use SSG instead.

Since then, missing keys are not saved to Locize anymore. It doesn't seem to be a misconfig on my side.

There are two issues:

1. `saveMissing` is not triggered on SSG pages (I don't know why)
1. When saveMissing is triggered (triggered randomly when on the only SSR page I've got), it fails with the API request with `ERR_FAILED` and no additional explanation

Debug mode is enabled on all pages.

- Code is at https://github.com/UnlyEd/next-right-now/blob/7ac2100303f9a0fc7595118e10e71d3dd5829361/src/utils/i18n/i18nextLocize.ts#L376
- Demo at https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-8co4x4lqx.now.sh/fr/products (use `i18n` in browser console to manipulate the i18nextInstance)

## 1 - `saveMissing` is not triggered on SSG pages

I don't know why, no logs are shown stating that missing keys are detected.

## 2 - API error `ERR_FAILED`

Browser console:
![image](https://user-images.githubusercontent.com/3807458/81353595-c10e7d80-90c9-11ea-9d63-16bddb857e1d.png)

I do get messages like `i18next::translator: missingKey fr common nav.productsPage.link Produits`, but nothing happens on Locize.

`saveMissing` is enabled and `apiKey` is provided.

The request seems to fail with `ERR_FAILED`, but no reason is given.

![image](https://user-images.githubusercontent.com/3807458/81425854-9c151b80-9158-11ea-9919-3f5c2b6f9aa1.png)

- Request URL: `https://api.locize.app/missing/658fc999-dfa8-4307-b9d7-b4870ad5b968/latest/fr/common`
- Payload: `{"nav.productsPage.link":"Produits","nav.githubDocPage.link":"Documentation","nav.adminSite.link":"Admin site"}`

**Comment by adrai** [comment]
401... not authorized...

**Comment by Vadorequest** [comment]
@adrai I've replicated the issue in #323 here.

Debug mode is enabled on the demo (https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-8co4x4lqx.now.sh/fr/products) with interactive `window.i18n` for testing, if needed.

**Comment by Vadorequest** [comment]
Why would I get a 401? It used to work. I'll check api key and project id.

**Comment by Vadorequest** [comment]
I don't know how/when, but keys got created in Locize, I just noticed it. (that's also why I can't reproduce "missing key" anymore), but I don't know how/what fixed it.

**Comment by adrai** [comment]
so is this ok now?

**Comment by Vadorequest** [comment]
Okay, so, to summarize:

- I got a 401 in development with `UnauthorizedException` `Error from cloudfront`
- Missing keys were created at some point (maybe on staging?) but I don't know why it worked nor when
- I created a new key and I do get `i18next::translator: missingKey fr common nav.fake.link fake` from the **browser** (localhost) but I'm still getting a 401

It's very hard to debug what happens because I don't know why I'm getting a 401.

**Comment by adrai** [comment]
The Api-Key you are using (starts with: 615...) is wrong!
The Api-Key that should work starts with e38...

**Comment by adrai** [comment]
Is it possible you are using the project-id as apiKey?

**Comment by Vadorequest** [comment]
You're right, I wasn't using the correct API Key.

I'll change it, but this doesn't explain how keys got created then, because I didn't create them manually and saveMissing was only enabled on localhost, where I was using the wrong api key so it shouldn't have been possible for those keys to be created.

**Comment by Vadorequest** [comment]
Using the correct API Key fixed the issue.

A small dev feedback:
- Lost lots of time because of this (2h), it should be made more obvious the issue was with the Api Key (better 401 error message maybe?). Also, I had disabled server logs (because too noisy) and I didn't understood the server was trying to create those missing keys first, and that why I couldn't always see the "i18next::translator: missingKey fr common nav.productsPage.link Produits" logs in the browser.
- I don't explain how keys got created while using a bad API Key.

Closing, thanks for the assistance!

**Comment by adrai** [comment]
...should have seen the 401 also without debug set to true

There are a few options how the keys were creeated:
- you used the correct api-key for a while
- you used the cli
- you uploaded/created them via locize UI

btw: this is how your namespace looked like already the 2nd of april:
![image](https://user-images.githubusercontent.com/1086194/81436978-ac35f680-916a-11ea-8be3-9654c7640b9b.png)
Which keys were missing?

**Comment by Vadorequest** [comment]
Yes, 401 isn't related to debug. But my point is the 401 wasn't self-explanatory and could be improved by stating "wrong api Key" for example.

I didn't use the cli nor created them through locize UI. The only way I'm using is the API, which used a wrong API key. (stored in a `.env.build` non-tracked file, so I don't have a good history revision available to compare changes)

Do you have a way to know when a key was created? I added `nav.productsPage.link` since then. (it's one of the keys that got created i-dont-know-how)

**Comment by adrai** [comment]
at: 2020-05-08T16:42:13.000Z
![image](https://user-images.githubusercontent.com/1086194/81439062-1308df00-916e-11ea-97c2-c717cbd22f26.png)
created via: POST /missing/658fc999-dfa8-4307-b9d7-b4870ad5b968/latest/fr/common

**Comment by Vadorequest** [comment]
Okay, thanks. So, they were created about 30mn before I noticed it (https://github.com/locize/i18next-locize-backend/issues/324#issuecomment-625921323), and I was definitely not using the right API key at this point because I updated it about 45mn later (https://github.com/locize/i18next-locize-backend/issues/324#issuecomment-625945674).

I don't explain it.
