### ISSUE TITLE
Warning when starting with react-native

### ISSUE THREAD

**Issue by maximilize** [locize/i18next-locize-backend#325]
I get this warning when starting the metro server:

```
warn Package i18next-locize-backend has been ignored because it contains invalid configuration. Reason: Package exports for 'node_modules/i18next-locize-backend' do not define a './package.json' subpath
```

However, everything is still working as expected.

**Comment by adrai** [comment]
Interesting... never seen this... and also not familiar with react-native.
Same here: https://github.com/facebook/react-native/issues/28710

Any help is welcome 🙏

**Comment by demchenkoalex** [comment]
Hi @adrai saw the similar issue in the UUID repo https://github.com/uuidjs/uuid/issues/444 and there is a PR by the library maintainers that has some discussion in it and supposedly fixes the warning https://github.com/uuidjs/uuid/pull/449 maybe this will help you, I believe this appears only in the repositories which support both Node and React Native environments for example.

**Comment by adrai** [comment]
Thanks for the info.
As I’m not familiar with react-native, can someone test if adding “./package.json” to the exports in the package.json file would help here?

**Comment by demchenkoalex** [comment]
Hi @adrai checked in our project, warning is no longer there. Opened a PR. Please double check if everything is ok in Node, I only checked React Native :)

**Comment by adrai** [comment]
Thank you very much.
Can you also check if this works in react-native, when requiring “i18next-locize-backend/cjs” ?

**Comment by adrai** [comment]
fyi: seems this makes no difference in Node

**Comment by adrai** [comment]
> Thank you very much.
> Can you also check if this works in react-native, when requiring “i18next-locize-backend/cjs” ?

@demchenkoalex as soon as you confirm I will merge the PR

**Comment by demchenkoalex** [comment]
Works with `import Locize from 'i18next-locize-backend/cjs'`

I did:
- installed Locize from my commit
- in `node_modules/'i18next-locize-backend` did `yarn` to install dev dependencies
- `yarn compile` to create `cjs` folder

**Comment by adrai** [comment]
released in v4.0.8

thank you very much for your help

**Comment by ctavan** [comment]
I think it might make more sense to actually fix this in `react-native` instead of adding this workaround to every single module on npm. If you agree, feel free to give your 👍 for https://github.com/react-native-community/cli/issues/1168

**Comment by demchenkoalex** [comment]
Not every single one (only the ones with node env supported) but yes, makes sense :)
