### ISSUE TITLE
constructor types break

### ISSUE THREAD

**Issue by Sunshine168** [locize/i18next-locize-backend#328]
https://github.com/locize/i18next-locize-backend/blob/master/lib/index.js#L80
https://github.com/locize/i18next-locize-backend/blob/master/index.d.ts#L66

```ts
constructor (services, options = {}, allOptions = {}, callback)
constructor(services?: any, options?: I18NextLocizeBackend.BackendOptions);
```

**Comment by adrai** [comment]
Can you try with v4.0.13 ?
