### ISSUE TITLE
Downloaded strings are not correctly applied. 

### ISSUE THREAD

**Issue by giovannimazzuoccolo** [locize/i18next-locize-backend#329]
We use i18next-locize-backend, i18next and react-i18next to translate our front-end, we have also an app in Flutter/Dart which it's downloading the strings with an XHR request and works properly.

For the last 2 days, the downloaded strings are not correctly applied on the front-end, if we enabled the debug on i18next the console give many of those warnings 

`i18next::translator: missingKey nl common global.logout Logout`

If I download the strings with axios from the locize server and apply them with `i18n.addResources(language, namespace, strings);` everything works well. 

This is our i18next.init
`import i18next from 'i18next';
import LocizeBackEnd from 'i18next-locize-backend';
// import LngDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

import moment from 'moment';
import { NameSpaces, Languages } from './locale';

// also import locales for moment
import 'moment/locale/de';
import 'moment/locale/fr';
import 'moment/locale/nl';

i18next
  // .use(LngDetector)
  .use(LocizeBackEnd)
  .use(initReactI18next)
  .init({
    fallbackLng: Languages.EN,
    // when saveMissing: false, missing keys are not uploaded
    // appendNamespaceToMissingKey: true, // let's see what this sends
    returnEmptyString: true, // rejects empty strings as valid translations
    languages: [Languages.EN, Languages.DE, Languages.FR, Languages.NL],

    // have a common namespace used around the full app
    ns: [NameSpaces.COMMON, NameSpaces.CUSTOMER, NameSpaces.HELP],
    defaultNS: NameSpaces.COMMON,

    backend: {
      projectId: 'b3...'
      // apiKey is only required if missing keys should be sent to locize
      // referenceLng: 'en'
    },

    // react does not need escapeValue
    interpolation: { escapeValue: false },

    // react-i18next configuration
    react: { wait: true, useSuspense: false }
  });

export default i18next;

i18next.on('languageChanged', function(lng) {
  moment.locale(lng);
  console.log('language has changed to: ', lng); // eslint-disable-line no-console
});
`

Let me know if you need a small repo to test that, I would be happy to set it up for you.

**Comment by adrai** [comment]
It's probably because of the key: "weather-widget.no-weather data" in your "common" namespace
Your project settings defines: publishFormat "auto" (so locize tries to detect if it should do nested or flat json format)
The key "weather-widget.no-weather data" has a space so we think this is natural language and publish with flat format.
More infos here: https://faq.locize.com/#/general-questions/why-is-my-namespace-suddenly-a-flat-json

**Comment by giovannimazzuoccolo** [comment]
That's correct, the white space was causing the issue. Thanks!
