### ISSUE TITLE
ReferenceError: Can't find variable: each

### ISSUE THREAD

**Issue by amitava82** [locize/i18next-locize-backend#330]
On Safari IOS 10.3.3 the library is throwing error `VM8681:15 ReferenceError: Can't find variable: each`. 

## To Reproduce
Try running a simple react app on Safari running on IOS 10.3.3

I'm looking at the code and it could be something to do with how each is used in utils.js
```
const arr = []
const each = arr.forEach
const slice = arr.slice
```

**Comment by adrai** [comment]
forEach seems to be supported in ios safari since version 1: https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
![image](https://user-images.githubusercontent.com/1086194/86903188-47b5fa00-c10f-11ea-8b62-fa28737d7e06.png)

Can you share more information?
stacktrace?

**Comment by amitava82** [comment]
Yes I know. I've been banning my head on it. I have all the polyfills as well.
There is nothing much in the stack trace. I'm 90 minutes into debugging this using Browserstack. This is all I have.
![Screenshot 2020-07-08 at 3 12 28 PM](https://user-images.githubusercontent.com/1279530/86903793-73e07380-c12d-11ea-9b85-351b54a9e0c6.png)

![Screenshot 2020-07-08 at 3 12 59 PM](https://user-images.githubusercontent.com/1279530/86903857-85c21680-c12d-11ea-83a9-113c6e3fc2b1.png)

**Comment by adrai** [comment]
Can you try to log this statement? `console.log([].forEach)`

**Comment by amitava82** [comment]
Yes it is undefined. Should have reported earlier.

**Comment by adrai** [comment]
and this? Array.prototype.forEach

**Comment by amitava82** [comment]
Actually I was wrong.  forEach does exist and supported in the ios safari version. Something else is going on. I replaced each and slice calls in following function:
```
export function defaults (obj) {
  [].forEach.call([].slice.call(arguments, 1), (source) => {
    if (source) {
      for (var prop in source) {
        if (obj[prop] === undefined) obj[prop] = source[prop]
      }
    }
  })
  return obj
}
```
Now I get a different unrelated error `ReferenceError: Can't find variable: hasLocalStorageSupportgetStorage`

Somehow I think the function the scope is messed up. Is there any demo repo I can quickly run to be sure this is actually issue with this library or some other issue in webpack/babel setup?

**Comment by amitava82** [comment]
Seems to work fine with a demo project so I'm guessing something else causing this.

**Comment by adrai** [comment]
interesting... curious to know what it is
