### ISSUE TITLE
Android long timer warning

### ISSUE THREAD

**Issue by marcusfroling** [locize/i18next-locize-backend#334]
## 🐛 Bug Report

Using the backend on an Android device results in a warning:

`Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setInterval with duration 3600000ms)`

## To Reproduce

Using a clean react native project:

1. Install i18next, i18next-locize-backend and react-i18next.
2. Add the following to App.js:

```js
import i18next from 'i18next';
import Locize from 'i18next-locize-backend';

i18next
  .use(Locize)
  .use(initReactI18next)
  .init({
    ...,
    backend: {
      projectId: PROJECT_ID,
      apiKey: API_KEY,
      reloadInterval: false,
    },
  });
```

## Expected behavior

Expected no warnings to be thrown

## Your Environment

- *runtime version*: node v14,
- *react-native*: 0.63.2
- *i18next-locize-backend*: 4.1.6
- *i18next*: 19.7.0
- *os*: Mac,

**Comment by adrai** [comment]
Can you try again with v4.1.7 ?

**Comment by marcusfroling** [comment]
Switching to v4.1.8 fixed it, thank you! 👍
