### ISSUE TITLE
Wrong constructor/init signature (or documentation issue)

### ISSUE THREAD

**Issue by andreialecu** [locize/i18next-locize-backend#336]
## 🐛 Bug Report

The documentation mentions that passing options to the constructor or to `init` should work as follows:

```ts
const locize = new Locize(options);
//or
const locize = new Locize();
locize.init(options);
```

However, that signature isn't valid.

```ts
  constructor(services?: any, options?: I18NextLocizeBackend.BackendOptions, callback?: I18NextLocizeBackend.LoadCallback);
  init(services?: any, options?: I18NextLocizeBackend.BackendOptions, callback?: I18NextLocizeBackend.LoadCallback): void;
```

Seems there's a `services` parameter that needs to be supplied first, which is not described at all.

## To Reproduce

See above.

## Expected behavior

Either the documentation should be updated or the types fixed. What is `services`?

## Your Environment

`i18next-locize-backend@npm:4.1.9`

**Comment by andreialecu** [comment]
Additionally, I believe this should be optional:

https://github.com/locize/i18next-locize-backend/blob/378a7c9a7be6c8ee97523c1b2b7ae024e8f7c881/index.d.ts#L66

I think it would be a good idea to rewrite this entire library using typescript. This way the types would be kept in sync automatically. It's 2021 after all. :)

**Comment by adrai** [comment]
Thank you for the inputs...
Internally, we decided to not use TypeScript at all.
This is why the types are not "really" 100% maintained.

Do you want to create a PR to fix the types?
btw: These types maybe are also not 100% correct: https://github.com/i18next/i18next-http-backend

**Comment by andreialecu** [comment]
I can open a PR, but what is services supposed to be for? Seems entirely undocumented.

Should it just be removed from the types if it's not documented? I noticed by reading the code that it is supposed to be optional.

Additionally:

I'm struggling a bit with the setup. I'm setting this up for a `react-native` app, but I'm not sure what the correct initialization should look like.

We already need to `use(initReactI18next)`. Should we chain it like `.use(initReactI18next).use(Locize)`? I tried that, but it seems not data reaches the dashboard. 🤔

**Comment by adrai** [comment]
Services are coming from i18next internals: https://www.i18next.com/misc/creating-own-plugins
https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L32
https://github.com/i18next/i18next/blob/master/index.d.ts#L725

Yes, i18next still needs to know what backend should be used, so you should `.use(Locize)`

Please have a look also at theses examples:
i18next react-native example: https://github.com/i18next/react-i18next/tree/master/example/react-native
More complete react tutorial: https://github.com/locize/react-tutorial

**Comment by andreialecu** [comment]
We're already using `react-i18next` successfully. We're just trying out Locize for managing the translations.

The examples linked don't show Locize + React integration. And I haven't been able to find any documentation on how to combine the two. I'll keep digging in the source to figure it out.

More documentation on this would be great though.

**Comment by adrai** [comment]
there is also another one: https://github.com/i18next/react-i18next/tree/master/example/locize

**Comment by adrai** [comment]
btw: a very short version is also on the locize landing page: https://locize.com/i18next.html

**Comment by andreialecu** [comment]
> btw: a very short version is also on the locize landing page: locize.com/i18next.html

The very short version there doesn't include React integration. I guess it wasn't clear that you could chain multiple `use()` calls and if the order matters.

It does link to a React tutorial indeed though below.

I was able to finally see network requests to `locize`. The problem appears to be that I was initializing it like:

```ts
i18next
  .use(initReactI18next)
  .use(LocizeBackend)
  .init({
    debug: true,
    resources, // this must be removed
    lng: locales[0].languageCode,
    fallbackLng: 'en',
    returnEmptyString: false,
    interpolation: {
      escapeValue: false,
    },
    backend: {
      projectId: '...',
      apiKey: '...',
      referenceLng: 'en',
    },
  });
```

If I'm already passing in the already existing translations via `resources` no network request to `locize` seem to occur. Is this expected? A warning or error at runtime might be helpful.

**Comment by adrai** [comment]
> If I'm already passing in the already existing translations via `resources` no network request to `locize` seem to occur. Is this expected? A warning or error at runtime might be helpful.

Yes, this is how i18next works.

https://github.com/i18next/i18next-http-backend/issues/55

**Comment by adrai** [comment]
https://www.i18next.com/how-to/add-or-load-translations#load-using-a-backend-plugin
![image](https://user-images.githubusercontent.com/1086194/111066376-00aeae80-84bf-11eb-9dd5-dfc2c3ae9dce.png)

**Comment by andreialecu** [comment]
I'm up and running. Thank you.

I've been looking at the types, and I noticed some issues which I'd like to bring to attention:

`i18next` itself has a leaky abstraction - link below:
https://github.com/i18next/i18next/blob/a6e09e32301d371092abf2d3bfed1ffa31db9a18/index.d.ts#L387-L391

The right way to solve this would for `i18next` to **not** define `backend`, but instead this package itself should augment `i18next` via:

```ts
declare module "i18next" {
  interface InitOptions {
    backend?: I18NextLocizeBackend.BackendOptions;
  }
}
```

That way it would be properly typed, and `i18next` can stay clean of leaky abstractions.

Unfortunately the above augmentation will only work if `backend` is removed from `i18next`, because you cannot override the type of a existing member. You can only add them if they don't exist.

So the proper fix here would be to remove `backend` (and other similar leaky fields) from `i18next` and instead augment them in via these plugins.

This may be a small breaking change for users if fixed, because they'd need to update both `i18next` and `i18next-locize-backend` to resolve any type errors. But it seems like the right thing to do.

Would you consider a PR that resolves this?

**Comment by andreialecu** [comment]
Note that all the other plugins options that are defined by the main `i18next` types have the same issue.

**Comment by adrai** [comment]
@pedrodurek may I ask what your opinion is regarding the types?

**Comment by andreialecu** [comment]
A somewhat related comment regarding improving types via type augmentation was recently posted here: https://github.com/i18next/i18next/issues/1504#issuecomment-742727015
