### ISSUE TITLE
Could not find a declaration file for module 'xliff'. #38

### ISSUE THREAD

**Issue by NagaSainath** [locize/i18next-locize-backend#341]
## 🐛 Bug Report

import xliff from 'xliff'
import xliff2js from 'xliff/xliff2js'

I can't do anyone of these, can anyone help me on this? is this still working? Appreciate your help

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *module version*: >=19.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
There is no xliff stuff in this github repo...
You maybe wanted to check: http://github.com/locize/xliff
