### ISSUE TITLE
Multiple requests to locize service on initial page load

### ISSUE THREAD

**Issue by iamskok** [locize/i18next-locize-backend#342]
## 🐛 Bug Report

Two requests are made to locize service on the initial page load.

 1. `en-US`
 2. `en`

The default language is set to `en-US` and `navigator.language` returns `en-US`.

![Screen Shot 2021-09-02 at 1 48 58 PM](https://user-images.githubusercontent.com/5145359/131895742-0c786c78-837e-4281-9ac0-623c36bc58e4.png)

## To Reproduce

[GitHub repo](https://github.com/iamskok/react-i18next-localize-test)

## Expected behavior

Make a single request to locize for the `en-US` locale on the initial page load.

## Your Environment

- *runtime version*:
  - node v14.17.5
  - Chrome Version 93.0.4577.63 (Official Build) (x86_64)
- *module version*:
  - "i18next-locize-backend": "^4.2.3",
- *os*: Mac

**Comment by adrai** [comment]
Yes, this is because of the i18next load option: https://www.i18next.com/overview/configuration-options
![image](https://user-images.githubusercontent.com/1086194/131897844-3584df23-973a-49f8-ad0c-2f3ed5c2a0b8.png)

Change it to 'currentOnly'

**Comment by iamskok** [comment]
Thanks a lot for such a quick response! It fixed both of the issues 🎉
