### ISSUE TITLE
Translation download fails on Android (React Native) 

### ISSUE THREAD

**Issue by mare95** [locize/i18next-locize-backend#344]
## 🐛 Bug Report

When i want to init translations on app mount `18next.init()` returns error `i18next::backendConnector: loading namespace translation for language en failed [TypeError: Network request failed]`.
This is only the case on android devices. On IOS devices translations are loaded

## To Reproduce

i18next config:
```js
import i18n, { type Translate } from 'i18next';
import { initReactI18next } from 'react-i18next';
import LocizeBackend from "i18next-locize-backend";
...

export const loadTranslations = () => {
  if(!i18next.isInitialized) {
    i18n
    .use(initReactI18next)
    .use(LocizeBackend)
    .init({
      debug: true,
      // needed because of flat json translations
      keySeparator: false,
      backend: {
        projectId: config.locize.projectId,
        apiKey: config.locize.apiKey,
        version: 'latest',
        refLng: 'en',
      },
      interpolation: {
        escapeValue: false
      },
      fallbackLng: 'en',
      saveMissing: true,
    });
  }
};
````

package json:
```
"react-native": "0.66.3",
"i18next": "^19.0.0",
"i18next-locize-backend": "^4.2.3",
```

## Expected behavior
Translations are loaded correctly from CDN without any errors.

## Your Environment
- *node*: v15.9.0
- *yarn*: 1.22.15
- *os*: Mac

**Comment by adrai** [comment]
Can you provide more information?
Does this occur on a real android device or only in simulator?
https://stackoverflow.com/questions/70043535/typeerror-network-request-failed-react-native-android-studio
Does this also occur if you directly call `fetch('https://api.locize.app/your-project-id/your-version/your-language/your-namespace')`?

**Comment by mare95** [comment]
No, it works when i call the endpoint separately, data is retrieved.
This is happening on android simulator, not sure about the real android device.
Also, the above works on IOS simulator.

Note that if i add `resources` option inside i18next.init()` with valid translations, everything works for both devices. 
But the idea is not to read translations from files. Instead i want to pull data from Locize CDN and to cache it using `i18next-async-storage-backend`.
As i said, this basic setup that i pasted in issue description works only on IOS simulator, android simulator has error when `resources` are not included and when i want to fetch data directly from the CDN.

All other requests are successful, there is no problem with simulator network connection.
This is simulator Cellular settings:
<img width="821" alt="Screenshot 2021-12-23 at 14 57 31" src="https://user-images.githubusercontent.com/17355348/147250373-0e1643b9-98bf-41f1-a1b7-5b930b2d6ff1.png">

**Comment by adrai** [comment]
Searching the web, it seems to be a known problem in the Android emulator... there's not much we can do here. sorry.
