### ISSUE TITLE
Locize backend removes boolean keys

### ISSUE THREAD

**Issue by Ibadichan** [locize/i18next-locize-backend#348]
## 🐛 Bug Report
Hello. I recently discovered that locize removes keys with the "boolean" type. Is it ok?

So if i want to upload the following file to locize:
```json
{
  "hello": true
}
```

The `hello` key will be deleted.

**Comment by adrai** [comment]
Keys with boolean values are created, but the value is ignored.

**Comment by Ibadichan** [comment]
Ok, thanks.

**Comment by adrai** [comment]
fyi: in the next service release, it will convert booleans, like numbers toString()
