### ISSUE TITLE
saveMissing is not working

### ISSUE THREAD

**Issue by jsflor** [locize/i18next-locize-backend#349]
## 🐛 Bug Report

When adding a new key/translation the saveMissing functionality is not working, I don't see networking in the devtools nor the new key being added in the locize web platform. Already fetching translations properly from locize service but not able to save new one in development

## To Reproduce

```
yarn create vite my-react-app --template react // Create generic vite react project
cd my-react-app && yarn
yarn add i18next i18next-browser-languagedetector i18next-locize-backend locize locize-lastused react-i18next // add required dependencies
```

Below is my i18n.ts config file
```js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import Backend from 'i18next-locize-backend';
// @ts-ignore
import LastUsed from 'locize-lastused';
// @ts-ignore
import { locizePlugin } from 'locize';

const isProduction = process.env.NODE_ENV === 'production';

const locizeOptions = {
  projectId: '81....e2',
  apiKey: '8c....b4',
  referenceLng: 'en',
  version: 'latest',
  allowedAddOrUpdateHosts: ['localhost'],
}

if (!isProduction) {
  // locize-lastused
  // sets a timestamp of last access on every translation segment on locize
  // -> safely remove the ones not being touched for weeks/months
  // https://github.com/locize/locize-lastused
  i18n.use(LastUsed);
}

i18n
  .use(locizePlugin)
  .use(Backend)
  .use(LanguageDetector) // detect user language
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    debug: !isProduction,
    fallbackLng: 'en',
    saveMissing: !isProduction, // you should not use saveMissing in production

    interpolation: {
      escapeValue: false // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
    },
    backend: locizeOptions,
    locizeLastUsed: locizeOptions,
  });
  
export default i18n;
```

lastly try to run the project and try to add a new translation 

## Expected behavior

When adding new translations in development they should be saved

## Your Environment

- *runtime version*: node v16.14.0, yarn v1.22.17
- *module version*: "i18next-locize-backend": "^5.1.2",
- *os*: Mac Big Sur 11.6.1
- dependencies:
    "i18next": "^21.8.16",
    "i18next-browser-languagedetector": "^6.1.4",
    "i18next-locize-backend": "^5.1.2",
    "locize": "^2.4.4",
    "locize-lastused": "^3.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^11.18.3",

**Comment by adrai** [comment]
Seems to work here...
Can you check the log?
set debug: true
check also if saveMissing is really set to true.

**Comment by jsflor** [comment]
@adrai my bad! was missing `allowedAddOrUpdateHosts: ['127.0.0.1'],` now is working properly thank you very much for your fast response!
