### ISSUE TITLE
Documentation bug/missing how to securely use this in production

### ISSUE THREAD

**Issue by goldylucks** [locize/i18next-locize-backend#350]
What is the use of this plugin if the only for it to work is exposing the api key and project id in the browser?

**Comment by jamuhl** [comment]
The api key is not needed during production. Depending on your env it can be only set for development build, eg. for react: https://github.com/locize/react-tutorial#step-4---production-version-with-caching

Reading those values from env: https://github.com/locize/react-tutorial/blob/main/step_4/src/i18n.js#L11

**Comment by adrai** [comment]
Other relevant information:
https://docs.locize.com/guides-tips-and-tricks/going-production
https://locize.com/blog/react-i18next/#production
https://github.com/locize/react-i18next-example-app

**Comment by goldylucks** [comment]
oh gotcha, wasn't clear to me from the docs
