### ISSUE TITLE
Angular SSR doesn't wait for requests

### ISSUE THREAD

**Issue by antkhnvsk** [locize/i18next-locize-backend#351]
## 🐛 Bug Report

We're using `i18next-locize-backend` with Angular application.
Recently we've activated SSR (Server Side Rendering) mode and found out that requests from `i18next-locize-backend` is out of scope of Angular zone (NgZone). SSR doesn't wait for lazy Locize translations and finished rendering before requests with translations come. As a result all text not rendered in SSR for SEO crawlers.

Perfect fix also would have possibility to provide a custom request function, because every Angular requests are going through it's httpClient, and we have additional benefits from it like request caching (once loaded translation chunks in SSR will be cached and sent to browser). Now this caching is also not worked by this reason, and we have doubled requests for translations for server-render and browser-render.

## To Reproduce
I've created a repo with reproduced behaviour https://github.com/antkhnvsk/angular-ssr-locize.
In README.md it's described how to run the project.
When we run project and look at it's Page Source we'll see untransformed translation keys (`login.actionSubmit`)

```
...
<app-lazy-page _nghost-sc18=""><p _ngcontent-sc18=""> login.actionSubmit
</p></app-lazy-page>
...
```

## Expected behaviour
Expected behaviour also provided as example in https://github.com/antkhnvsk/angular-ssr-locize.
Switching `USE_CUSTOM_PATCHED_BACKEND` to `true` in [https://github.com/antkhnvsk/angular-ssr-locize/src/app/app.module.ts](https://github.com/antkhnvsk/angular-ssr-locize/src/app/app.module.ts) we could see the desired behaviour.

```
...
<app-lazy-page _nghost-sc18=""><p _ngcontent-sc18=""> Anmelden
</p></app-lazy-page>
...
```

**Comment by adrai** [comment]
Sorry, I'm not really familiar with angular...
Why does it work when using the setInterval?

How would the angular http client be used?
Imagine a similar interface like the one for i18next-http-backend: https://github.com/i18next/i18next-http-backend#backend-options
<img width="768" alt="image" src="https://user-images.githubusercontent.com/1086194/217531959-480076b7-8820-46cf-bdc1-21ebc1ba7fc0.png">

**Comment by antkhnvsk** [comment]
The way it done in `i18next-http-backend` would be the perfect solution. 😊
As we're already using it as fallback in a chain, and it's works well with custom `request` function where we provide httpClient. It's also works in SSR.

Would it be helpful, if i'll add our custom request function as example to my example repo?

----
> Why does it work when using the setInterval?

It works with setInterval because Angular monkey patched setInterval function, and wait for it's execution.
It works same for JS request functions, they're patched too, but by some reason requests defined from i18next-locize-backend are not use this patched functions, and not visible to Angular.

**Comment by adrai** [comment]
Just published v6.2.0

Something like this should work:

```ts
    const locizeBackendOptions = {
      projectId: 'project-id',
      reloadInterval: false,
      request: (info: any, callback: (err: any, data?: any) => void) => {
        const headers = new HttpHeaders()
        Object.keys(info.headers).forEach((k) => {
          headers.set(k, info.headers[k])
        })
        httpClient.request(info.method, info.url, {
          body: info.body ? JSON.stringify(info.body) : undefined,
          headers
        }).subscribe((ret) => {
          callback(null, { status: 200, data: ret })
        }, (err) => callback(err));
      },
    };
```

let me know

**Comment by antkhnvsk** [comment]
Thank you for quick response!

It does work, both callback and promise ways.
I've pushed worked version to my example repo.

The only question, could interfaces `CustomRequestOptions, RequestResponse, RequestCallback` also be exportable? I've to copy-paste it otherwise.

**Comment by adrai** [comment]
Do you like to provide a PR?

**Comment by adrai** [comment]
v6.2.1 should export those types

**Comment by antkhnvsk** [comment]
Many thanks, @adrai 🙏
