### ISSUE TITLE
Change version in runtime after initialization

### ISSUE THREAD

**Issue by khashashin** [locize/i18next-locize-backend#353]
## 🚀 Feature Proposal

Add an API to change the `version` at runtime (e.g., via a method like `updateVersion(newVersion))`, allowing developers to switch between different translation versions without having to reinitialize i18next or restart their server

## Motivation

Some apps need to switch between various translation `version`s in real time (e.g., staging vs. production, or different releases).

## Example

Let’s say you want to let users pick which `version` of translations to use based on a query parameter.

**Comment by adrai** [comment]
I don't think it's a optimal idea to switch version at runtime. This would potentially get problems in the i18next resource store.
If you really need to target different versions at runtime, I recommend creating dedicated i18next instances. That way the resource store etc. will stay consistent.

**Comment by khashashin** [comment]
Wouldn't be possible to reload resources after version change?

https://www.i18next.com/overview/api#reloadresources

**Comment by khashashin** [comment]
Using instances also works, thanks for pointing that out, I didn't thought of that this way. I ended up using the following method
```javascript
import i18next from "i18next";
import Backend from "i18next-locize-backend";

const i18nVersionMap = {
  prod: "latest",
  staging: "staging",
  dev: "development",
};

const i18nInstances = {};

/**
 * Returns an i18next instance configured for the given version.
 * If the instance already exists, it is returned from the cache.
 * Otherwise, a new instance is created and initialized.
 */
async function getI18nForVersion(version) {
  if (!i18nVersionMap[version]) {
    // Fallback to 'prod' if version not recognized
    version = "prod";
  }

  // Check if we've already created an instance for this version
  if (i18nInstances[version]) {
    return i18nInstances[version];
  }

  // Otherwise, create a new instance
  const instance = i18next.createInstance();

  await instance.use(Backend).init({
    backend: {
      projectId: "asdasd",
      version: i18nVersionMap[version],
      referenceLng: "de-CH",
    },
    fallbackLng: "de-CH",
    supportedLngs: ["de-CH", "it-CH", "fr-CH"],
    preload: ["de-CH", "it-CH", "fr-CH"],
    ns: ["asdasd", "asdasd_v4"],
  });

  i18nInstances[version] = instance;
  return instance;
}

export { getI18nForVersion };

```

**Comment by adrai** [comment]
Yes, using dedicated instances is for sure more secure.
But If you really want to go the way with just 1 instance, you can change the version like this:

Option 1)
```js
i18next.services.backendConnector.backend.options.version = 'production'
i18next.reloadResources()
```


Option 2)
```js
const backend = new LocizeBackend(
  backendOptions,
  (err, opts) => {
    if (err) return console.error(err)
    i18next
      .use(backend)
      // yourOptions should not include backendOptions!
      .init({ ...opts, ...yourOptions}, (err, t) => {
        if (err) return console.error(err)

        backend.options.version = 'production'
        i18next.reloadResources()
      })
  }
)
```
